sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-002
env:
  global:
    -
      # LTD_AWS_ID
      secure: G2b9d1sifMOJbeahKK5x/kG1F9/KBt+HHQB6baYQCWeS1kCgmTuFcJp8BI10XGVJ+8zMC5C0gB7tWSflMfRx3ANoLmuSojaotKkyyNOcaJ3m3NtkY8IPLBtEojb99xBFMP8T9dvwSZu60Tdv86Lp9oKjvZrGD6nNzxcEHDcg9KXikYNzwZ/HrHWR5mOj0qUX/+thrlWpC/TKqRt5//Gi8WSXHBDD5YrD0xg78h57+Y8po/ekt5iy0AStcwa6VJ0wG/4mByb5OiTwYyb4x7m735jFxOJT8x2LFZOVeoWRz7SCDuwZHhc8AFkEgwH2rUsP1W3M1okcTl7l6e+LhvIGhr10GDfZHUTe9nJpkYfFpeMGZvaeP0oxPHOxl01KKBg8Zult7snRKgVZLtmlwXtpP0VhXmi8sQ3Yr263NKs0kR/0RVC0awGGiQWEjuYGaGqzTT2Xmup9ep5eGolXK0aLRLi0SC7Yq0IaGfT7YB3PqmlHg4APYIjzw0edSoMDDHO5rSuWZjTQw8v+mZEYfb+2+pFack7FF59PyFn9DrGgui0PBD5oU+UQt+3xnL+cJsGpw3Dzkz1J7R6VmQ2uSKv6I9/wowZcUYrKzRMy6tY2BuAf+8p+50xQ57y7Du2sb4ZvK1RO8jp5g26Qdoju1NW2rXDPkQS70yMka5fZbMxyDWM=
    -
      # LTD_AWS_SECRET
      secure: MSpNqfGBwhubIUKbeq+Q9NG3yk35/4bSJWXDpntAJ+JgKl8Gwi+cvDSJs5tZaZGY0gaC/nw3l3nUsQK9BtwQiYCzGswQPZb/rR+M3VOv8PjKEwA/upNP9ejAVigwo8l0uDjxTD0iCQLm8+D/hdxr5nqH4oppSHV1jCLY84h7UhSAavxjJ8OmWThRsVA1x5Pfe4INPmkYMH/HYqQ2nNC9/EmA+Gp3IcBx0H8oa6uAp6i8lfrSMcbi5KfEuYu2zQKRlMSKCp4tbetX5AHPM5VVkY0hwWVoEqilvhkq03pVoSEVrE7t168Xyr5Xhb1hjCHlXejS3qSY91nVS/kNeSkC8sUqtED/vwTkOwGdOg8GmYDXcJ9UITcoibHUqVAAIZ0MiQ3FlL2wkCuy3hzZdbn0DGfR95ediIzOpFfaIPM4oQAWBqIGsKPNA87d/dq0wd40OcO42rInwOidIkApEZceH0Dv90XpwAP2BzDwuouORWR8yq89FkOZvEWYD6gosON7I6Bbfu+pflZrf2eBmOHT4FH3tWQ3gvmYuS3CeRCrASbv3lItnG4BKL6wQ+VkvItU08sY/cTAT1B8qmroLWTOI97u3wA1tpk9xsjVI6ga16gSTM0cj2jPbRdPY+xgi6K7dLnE44xqMdBt1RqiW/WZaUcZDemRmC1dcnstUtpbWA4=
    -
      # LTD_USERNAME
      secure: X/ssuD3PjV6LjM0Otg70H0D37eikS6HbIcVtym+VNjyUutCyZ65X5r6ApLSBzI4br8i+2VenqWMv2cxBS5O2lK0Lmv9j2RUFugZ5DX75Q1PFK21tURX73teYJQuSk/AZlph9v6mxOgZOZ75cra3SYwQ4amNY8zQVtTm0XeU1lDS2Y4qaVArWXOCBpEPQJ9kt3QrXuqOECom1UT+Q6qqXAxr3crIXAFjJjdKK3M+Wa8StG2fy7ucFFEEQ5qrOsm2lkr/I7+xD90M+jgQeoyOLXF31SO7tNR/Q++BpDaJFweDrdmfsj7ClvWBrMLBrM4gbJMj9V8CTIIPeA3l2kwqcYY2sRnaUe/b3ctFGvkqVDWwNNiGAEZ34PRL/O4smKBRzyGBXtPDPYlQagKYu1wO7Hn9eZOsJkvmaCuYteRt3TEX4zytCS2HyytLiLAaqtRSu7GcfzciyefXSjg1Uonn9JHU4GJ0XONWHp3jRhMF5gjwjcjbKnfvsgRJo9fQANSvJkkI8aRPcQ4m3iOyQeANsHu+UzE6/uKuIQMI9b7L2sm+vqztpkaKKH9nSLEYAX9I5ZzCRMH4qsI7Cc3HCh5jF6qLjAvFhTz9lltOak0hsPAosJAa39l+CS4epqUcFyAqF7cT8w3vlWxD783WP2hhbr+dGENpDD007XJBi3qLisjE=
    -
      # LTD_PASSWORD
      secure: INx/pEZc/ISA158o8CxbpawWPRrx0c+/F7A9pGPQOPBa1W/P/kG2ebrC3+v0EmVY0lEp5uWrNkrvdPA4/8sKPcxe7MuLU8v4Y+bi680ajosjYM6WEuY+lcT5llRSUoV2F1zvzSfKfpUxd64q2zXOy6iiO1cLuPn3obuqZjPXNI+Gke3ac/SonlLrFmrjCjMaxU6DYem/4Zi1G7rW6rhPs4rVFXz4UJGATE0xr739J+h8nNlQnxJqyWBRXoDoQr0DbZOQ1KkhZ0hX/7aYOez7VSCATZsUHwbCfUhp6qPsCjKp2002e5nyE9rNnPUSZlWTQ6VtBMEGTLReb58Ucf5twfeoHN8sNuz30+4n71rc/IPnzWFXf7OG9dp29JRtGaoIumYcXe4uMz9pEbrpn/jN93zhuRiGCXn2JZf4lMwoikELcGPqV4d4PyS28qw/b7e8JPPkqOjXsF/F8bTkZsnRAaxbraBMGzrzPAUpH5N4CoFUFuIwE4P/D/oO8rJqtE4tenC055W1zoHfisGRze2X/507Zh1dklHYfWv1TD1lcC0vhf0P2KZnwETWZ6YHYEBp59M2omWUqGa4hmleQrP4MKvgaHn49EEgLiatwlBipH9zU7w/6Q1JxwvjZ9Mng/g+8p81qF+3k+LAWzrePNG6xzYxY7VOXkmBNewLeAvlCaI=
